export const ORDER_TYPE = Object.freeze({
  DELIVERY: 'DELIVERY',
  PREORDER: 'PREORDER',
  RESERVATION: 'RESERVATION',
});

export const PAYMENT_METHOD = Object.freeze({
  PAY_ON_APP: 'PAY_ON_APP',
  PAY_LATER: 'PAY_LATER',
});

export const ORDER_STATUS = Object.freeze({
  CREATED: 'CREATED',
  PAID: 'PAID',
  DELIVERED: 'DELIVERED',
  OBTAINED: 'OBTAINED',
  FINISHED: 'FINISHED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const PAYMENT_STATUS = Object.freeze({
  UNPAID: 'UNPAID',
  PENDING: 'PENDING',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});
