export const RESTAURANT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_SUBSCRIPTION: 'PENDING_SUBSCRIPTION',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  ARCHIVED: 'ARCHIVED',
  CLOSED: 'CLOSED',
});

export const SUBSCRIPTION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
});

export const RESTAURANT_VISIBILITY = Object.freeze({
  HIDDEN: 'HIDDEN',
  PUBLIC: 'PUBLIC',
});

export const VERIFICATION_STATUS = Object.freeze({
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
});

export const ACTIVATION_BLOCKERS = Object.freeze({
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
});

