export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  EMBEDDING_PROVIDER_FAILED: 'EMBEDDING_PROVIDER_FAILED',
});

