export const USER_STATUS = Object.freeze({
  PENDING_EMAIL_VERIFICATION: 'PENDING_EMAIL_VERIFICATION',
  PENDING_PHONE_VERIFICATION: 'PENDING_PHONE_VERIFICATION',
  PENDING_FACE_ACTIVATION: 'PENDING_FACE_ACTIVATION',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
});

export const USER_STATUS_LIST = Object.freeze(Object.values(USER_STATUS));

